package TaskManager::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'TaskManager::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:taskmanager.db',
        user => '',
        password => '',
    }
);

=head1 NAME

TaskManager::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<TaskManager>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<TaskManager::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Nora Cook

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
